version: "3.4"
services:
    web:
        image: "docker.pkg.github.com/tinohager/booklibrary.management/booklibrary:latest"
        ports:
            - "8000:80"
        depends_on:
            - db
        environment:
            ConnectionStrings:BookLibraryManagement: "Server=db;Database=BookLibraryManagement;User Id=sa;Password=Secure-Password.1234;"
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Secure-Password.1234"
            ACCEPT_EULA: "Y"
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
            interval: 10s
            timeout: 3s
            retries: 10
            start_period: 10s