# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src/BookLibrary.Management.Spa

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean slate
      run: npm ci
      working-directory: ${{env.working-directory}}
    - name: Build
      run: npm run build --if-present
      working-directory: ${{env.working-directory}}
#    - name: Test
#      run: npm test
#      env:
#        CI: true

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: spa
        # Directory containing files to upload
        path: ${{env.working-directory}}/dist/
